services:
  perfsonar-downloader:
    build: 
      context: ./Dockerfiles
      dockerfile: Dockerfile-downloader
    container_name: perfsonar-downloader
    volumes:
      - perfsonar_logstash:/usr/lib/perfsonar/logstash
      - perfsonar_archive:/usr/lib/perfsonar/archive
      - perfsonar_dashboards:/usr/lib/perfsonar/dashboards
    environment:
      - PERFSONAR_VERSION=5.2.0
    restart: "no" # This container runs once to download & install
  
  opensearch-node:
    build:
      context: ./Dockerfiles/archive
      dockerfile: Dockerfile
    container_name: opensearch-node
    depends_on:
      - perfsonar-downloader
    environment:
      OPENSEARCH_VERSION: ${OPENSEARCH_VERSION}
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "perfSONAR123!"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      cluster.name: opensearch-cluster
      node.name: opensearch-node
      discovery.type: single-node
      bootstrap.memory_lock: "true"            # disables swapping
      network.host: "0.0.0.0"                  # required for non-demo config
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - perfsonar_logstash:/usr/lib/perfsonar/logstash
      - perfsonar_archive:/usr/lib/perfsonar/archive
      - opensearch_data:/usr/share/opensearch/data
      - opensearch_config:/usr/share/opensearch/config
    ports:
      - "9200:9200"
      - "9600:9600" # required for Performance Analyzer
    restart: always

  logstash:
    build: 
      context: ./Dockerfiles/logstash
      dockerfile: Dockerfile
    container_name: perfsonar-logstash
    depends_on:
      - perfsonar-downloader
      - opensearch-node
    environment:
      LOGSTASH_VERSION: ${LOGSTASH_VERSION}
      MONITORING_ENABLED: "false"
      LOG_LEVEL: info
      RATE_CACHE_MAX_ENTRIES: 10000000
      RATE_CACHE_EXPIRES: 600
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - perfsonar_logstash:/usr/lib/perfsonar/logstash
      - logstash_config:/usr/share/logstash/config/
    ports:
      - 11283:11283
    expose:
      - "11283"
    restart: always

  opensearch-dashboards:
    build:
      context: ./Dockerfiles/dashboards
      dockerfile: Dockerfile
    container_name: opensearch-dashboards
    depends_on:
      - perfsonar-downloader
      - opensearch-node
    environment:
      OPENSEARCH_VERSION: ${OPENSEARCH_VERSION}
      OPENSEARCH_HOSTS: '["https://opensearch-node:9200"]' # must be a string with no spaces when specified as an environment variable
    volumes:
      - perfsonar_archive:/usr/lib/perfsonar/archive
      - perfsonar_dashboards:/usr/lib/perfsonar/dashboards
      - dashboards_config:/usr/share/opensearch-dashboards/config/
    ports:
      - 5601:5601
    expose:
      - "5601"
    restart: always

volumes:
  perfsonar_logstash:
  perfsonar_archive:
  perfsonar_dashboards:
  opensearch_data:
  opensearch_config:
  logstash_config:
  dashboards_config: