{{- range $userName, $userConfig := .Values.perfsonarUsers }}
{{- if and $userConfig.generatePassword.enabled (not $userConfig.existingSecretName) }}
{{- $secretName := tpl $userConfig.generatePassword.secretName $ }}
{{- $secretKey := $userConfig.generatePassword.secretKey | default "password" }}
{{- $passwordLength := $userConfig.generatePassword.passwordLength | default 16 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "perfsonar-archive-config-es.labels" $ | nindent 4 }}
type: Opaque
data:
  {{ $secretKey }}: {{ randAlphaNum $passwordLength | b64enc }}
---
{{- end }}
{{- end }}

{{- if and .Values.logstashProxyUser.enabled .Values.logstashProxyUser.generatePassword.enabled (not .Values.logstashProxyUser.existingSecretName) }}
{{- $secretName := tpl .Values.logstashProxyUser.generatePassword.secretName . }}
{{- $secretKey := .Values.logstashProxyUser.generatePassword.secretKey | default "password" }}
{{- $passwordLength := .Values.logstashProxyUser.generatePassword.passwordLength | default 16 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "perfsonar-archive-config-es.labels" . | nindent 4 }}
type: Opaque
data:
  {{ $secretKey }}: {{ randAlphaNum $passwordLength | b64enc }}
---
{{- end }}