version: '3'
services:
  opensearch-node:
    image: "opensearchproject/opensearch:${OPENSEARCH_VERSION_LONG}"
    container_name: opensearch-node
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms16g -Xmx16g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - network.host=0.0.0.0 # required if not using the demo security configuration
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      
      - ./archive/certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem ## need to make sure i can mount this as volume instead (i.e. there are no other files in this path from the original image)
      - ./archive/certs/root-ca.der:/usr/share/opensearch/config/root-ca.der
      - ./archive/certs/node.pem:/usr/share/opensearch/config/node.pem
      - ./archive/certs/node-key.pem:/usr/share/opensearch/config/node-key.pem
      - ./archive/certs/admin.pem:/usr/share/opensearch/config/admin.pem
      - ./archive/certs/admin-key.pem:/usr/share/opensearch/config/admin-key.pem
      - ./archive/configs/opensearch.yml:/usr/share/opensearch/config/opensearch.yml

      - ./archive/configs/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
      - ./archive/configs/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
      - ./archive/configs/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
      - ./archive/configs/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: "opensearchproject/opensearch-dashboards:${OPENSEARCH_VERSION_LONG}"
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node:9200"]' # must be a string with no spaces when specified as an environment variable
    volumes:
      - ./configs/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    networks:
      - opensearch-net
  logstash:
    image: "opensearchproject/logstash-oss-with-opensearch-output-plugin:${LOGSTASH_VERSION}"
    container_name: logstash
    environment:
      - MONITORING_ENABLED=False
      - LOG_LEVEL=info
      - RATE_CACHE_MAX_ENTRIES=10000000
      - RATE_CACHE_EXPIRES=600
    env_file:
      - path: ./logstash/.env
    ports:
      - 11283:11283
    expose:
      - "11283"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./logstash/configs/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/pipeline/:/usr/lib/perfsonar/logstash/pipeline/
      - ./logstash/prometheus_pipeline/:/usr/lib/perfsonar/logstash/prometheus_pipeline/
      - ./logstash/ruby/:/usr/lib/perfsonar/logstash/ruby
      - ./logstash/java/:/usr/lib/perfsonar/logstash/java
    networks:
      - opensearch-net
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    expose:
      - "3000"
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net: