services:
  preconfiguration:
    image: perfsonar-archive-configuration
    build:
      context: .
      dockerfile: Dockerfile-configuration
    container_name: preconfiguration
    working_dir: /home
    environment:
      - PERFSONAR_VERSION=5.2.0
      - OPENSEARCH_VERSION=2.18
      - OPENSEARCH_VERSION_LONG=2.18.0
    volumes: #use volumes instead, so it should works with kubernetes
      - ./logstash:/home/logstash
      - ./archive:/home/archive
      - ./dashboards:/home/dashboards
    command: [ "pre" ]
  postconfiguration:
    image: perfsonar-archive-configuration
    build:
      context: .
      dockerfile: Dockerfile-configuration
    container_name: postconfiguration
    working_dir: /home
    network_mode: "host"
    volumes:
      - ./logstash:/home/logstash
      - ./archive:/home/archive
    command: [ "post" ]