version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss:10.2.1
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_INSTALL_PLUGINS=grafana-opensearch-datasource
    ports:
     - '3000:3000'
    volumes:
     - 'grafana_storage:/var/lib/grafana'
volumes:
  grafana_storage: {}